---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  memberOf: [guests, OCR-TEAM]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: Taylor
spec:
  memberOf: [OCRTEAM, MLENABLEMENT]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: James
spec:
  memberOf: [MLTEAM]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: "OCRTEAM"
spec:
  type: team
  children: []
  profile:
    displayName: OCRTEAM
    email: ocr_team@fin.org
    picture: https://example.com/groups/bu-infrastructure.jpeg
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: "mlteam"
  description: The infra business unit
spec:
  type: business-unit
  children: []
  profile:
    displayName: MLTEAM
    email: ML_team@fin.org
    picture: https://example.com/groups/bu-infrastructure.jpeg
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: "MLENABLEMENT"
spec:
  type: team
  children: [OCRTEAM]
  profile:
    displayName: MLENABLEMENT
    email: ML-ENABLEMENT@fin.org
    picture: https://example.com/groups/bu-infrastructure.jpeg
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: Bilbo
spec:
  memberOf: [EXAM]
  profile:
    displayName: Bilbo
    email: Bilbo@fin.org
    picture: https://static.wikia.nocookie.net/middlearthfilmsaga/images/7/7e/Bilbo_BOFA_12.png/revision/latest?cb=20190220214510
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: "EXAM"
spec:
  type: team
  children: [EXAM]
  profile:
    displayName: EXAM
    email: EXAM@fin.org
    picture: https://example.com/groups/bu-infrastructure.jpeg
